/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package betaproyecto;

import java.awt.Graphics;

/**
 *
 * @author veronica
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inpAncho = new javax.swing.JTextField();
        inpLargo = new javax.swing.JTextField();
        btnLaberinto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ancho:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Largo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel1.add(inpAncho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, -1));
        jPanel1.add(inpLargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, -1));

        btnLaberinto.setText("Crear laberinto");
        btnLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaberintoActionPerformed(evt);
            }
        });
        jPanel1.add(btnLaberinto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaberintoActionPerformed
        // TODO add your handling code here:
        //try {
            Integer Ancho = Integer.parseInt(inpAncho.getText());
            Integer Largo = Integer.parseInt(inpLargo.getText());
            Integer count = Ancho * Largo * 100;
            Lista mLista = new Lista();
            Lista marco = new Lista();
            mLista = mLista.crearMLista(Ancho, Largo);
            marco = marco.crearMarco(mLista.getpFirst(), Ancho, Largo);
            mLista.Prim(mLista, count);
            marco.marcarEntrada(marco, Ancho + 2, Largo + 2);
            marco.marcarSalida(marco, Ancho + 2, Largo + 2);
            Matriz matriz = new Matriz();
            matriz.setCeldas(matriz.crearMatriz(matriz.getCeldas(), Ancho + 2, Largo + 2));
            matriz.ingresarValores(matriz.getCeldas(), mLista);
            matriz.ingresarValoresMarco(matriz.getCeldas(), marco);
            Laberinto lab = new Laberinto(Ancho + 2, Largo + 2, matriz.getCeldas());
            Ventana ventana = new Ventana(lab);
            ventana.crearVentana(ventana, marco, mLista);
            //for (int i = 0; i < 5; i++) {
                //System.out.println(pAux.getFrontera() + " " + pAux.getpEste().getFrontera() + " "+ pAux.getpEste().getpEste().getFrontera() +" "+ pAux.getpEste().getpEste().getpEste().getFrontera());
               // pAux = pAux.getpSur();
            
            //}

            
        //} catch (Exception e) {
            //System.out.println("xD");
        //}

    }//GEN-LAST:event_btnLaberintoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaberinto;
    private javax.swing.JTextField inpAncho;
    private javax.swing.JTextField inpLargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
